// Central state machines shared by control-plane, node-agent and panel.
// Keeping these in one place avoids "estados impossiveis" spread across the codebase.

export const ServerStatus = Object.freeze({
  CREATING: "CREATING",
  INSTALLING: "INSTALLING",
  STOPPED: "STOPPED",
  STARTING: "STARTING",
  RUNNING: "RUNNING",
  STOPPING: "STOPPING",
  RESTARTING: "RESTARTING",
  CRASHED: "CRASHED",
  RECOVERING: "RECOVERING",
  BACKING_UP: "BACKING_UP",
  RESTORING: "RESTORING",
  SUSPENDED: "SUSPENDED",
  DELETING: "DELETING",
  DELETED: "DELETED",
  ERROR: "ERROR",
});

// Allowed transitions. Anything not listed here is rejected by the state machine
// helper in control-plane/src/services/serverStateMachine.js
export const SERVER_TRANSITIONS = Object.freeze({
  CREATING: ["INSTALLING", "ERROR", "DELETING"],
  INSTALLING: ["STOPPED", "ERROR", "DELETING"],
  STOPPED: ["STARTING", "BACKING_UP", "RESTORING", "DELETING", "SUSPENDED"],
  STARTING: ["RUNNING", "CRASHED", "ERROR", "STOPPED", "DELETING"],
  // RUNNING -> DELETING covers "force delete while online": deleteServer()
  // in serverLifecycle.js always force-stops+removes the container via the
  // agent regardless of the server's prior state, so allowing this
  // transition doesn't leave a container running behind a DELETED record.
  RUNNING: ["STOPPING", "CRASHED", "RESTARTING", "BACKING_UP", "DELETING"],
  STOPPING: ["STOPPED", "ERROR", "DELETING"],
  RESTARTING: ["RUNNING", "CRASHED", "ERROR", "DELETING"],
  CRASHED: ["RECOVERING", "STOPPED", "ERROR", "DELETING"],
  RECOVERING: ["STARTING", "STOPPED", "ERROR", "DELETING"],
  BACKING_UP: ["STOPPED", "RUNNING", "ERROR"],
  RESTORING: ["STOPPED", "ERROR"],
  SUSPENDED: ["STOPPED", "DELETING"],
  DELETING: ["DELETED", "ERROR"],
  DELETED: [],
  ERROR: ["STOPPED", "DELETING", "RECOVERING"],
});

export const NodeStatus = Object.freeze({
  PENDING: "PENDING", // registered but never heartbeated
  ACTIVE: "ACTIVE",
  MAINTENANCE: "MAINTENANCE",
  DRAINING: "DRAINING",
  OFFLINE: "OFFLINE",
});

export const OrderStatus = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  DECLINED: "DECLINED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
  PROVISIONING: "PROVISIONING",
  PROVISIONED: "PROVISIONED",
  FAILED: "FAILED",
});

export const JobType = Object.freeze({
  PROVISION_SERVER: "PROVISION_SERVER",
  START_SERVER: "START_SERVER",
  STOP_SERVER: "STOP_SERVER",
  RESTART_SERVER: "RESTART_SERVER",
  DELETE_SERVER: "DELETE_SERVER",
  BACKUP_SERVER: "BACKUP_SERVER",
  RESTORE_BACKUP: "RESTORE_BACKUP",
  RECONCILE: "RECONCILE",
});

export const JobStatus = Object.freeze({
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
});

export const AuditEvent = Object.freeze({
  USER_CREATED: "USER_CREATED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_BLOCKED: "USER_BLOCKED",
  USER_UNBLOCKED: "USER_UNBLOCKED",
  SERVER_CREATED: "SERVER_CREATED",
  SERVER_STARTED: "SERVER_STARTED",
  SERVER_STOPPED: "SERVER_STOPPED",
  SERVER_RESTARTED: "SERVER_RESTARTED",
  SERVER_DELETED: "SERVER_DELETED",
  SERVER_SUSPENDED: "SERVER_SUSPENDED",
  SERVER_UNSUSPENDED: "SERVER_UNSUSPENDED",
  BACKUP_CREATED: "BACKUP_CREATED",
  BACKUP_RESTORED: "BACKUP_RESTORED",
  BACKUP_DELETED: "BACKUP_DELETED",
  PLAN_CHANGED: "PLAN_CHANGED",
  ORDER_CREATED: "ORDER_CREATED",
  PAYMENT_APPROVED: "PAYMENT_APPROVED",
  PAYMENT_DECLINED: "PAYMENT_DECLINED",
  ADMIN_LOGIN: "ADMIN_LOGIN",
  ADMIN_ACTION: "ADMIN_ACTION",
  NODE_REGISTERED: "NODE_REGISTERED",
  NODE_ONLINE: "NODE_ONLINE",
  NODE_OFFLINE: "NODE_OFFLINE",
  NODE_MAINTENANCE: "NODE_MAINTENANCE",
  FILE_UPLOADED: "FILE_UPLOADED",
  FILE_DELETED: "FILE_DELETED",
  ENV_VAR_UPDATED: "ENV_VAR_UPDATED",
  DOMAIN_ADDED: "DOMAIN_ADDED",
  DOMAIN_REMOVED: "DOMAIN_REMOVED",
});

export function canTransition(from, to) {
  const allowed = SERVER_TRANSITIONS[from];
  return Array.isArray(allowed) && allowed.includes(to);
}
